[build]
  command = "npm install && cd webapp && npm install && npm run build && cd .. && pip install -r mpla_project/requirements.txt -r server/requirements.txt && cd mpla_project && pip install -e . && cd .."
  functions = "server"
  publish = "webapp/dist"

[build.environment]
  NODE_ENV = "production"
  PORT = "8080"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/start"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 